# Generated by Django 4.2.7 on 2026-04-27 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0003_journalentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip_params', models.JSONField(default=dict, help_text='Trip parameters (mood, interests, budget, etc)')),
                ('final_mood', models.CharField(choices=[('RELAXING', 'Relaxing'), ('SPIRITUAL', 'Spiritual'), ('HISTORICAL', 'Historical'), ('FOODIE', 'Foodie'), ('FUN', 'Fun'), ('SHOPPING', 'Shopping'), ('NATURE', 'Nature'), ('ROMANTIC', 'Romantic'), ('FAMILY', 'Family')], help_text='Final mood determined by AI', max_length=20)),
                ('stages_log', models.JSONField(default=dict, help_text='Results from each stage (emotion detection, ML ranking, LLM enhancement)')),
                ('generation_latency_ms', models.FloatField(default=0, help_text='Total generation time in milliseconds')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('fallback', 'Fallback')], default='success', max_length=20)),
                ('itinerary_preview', models.JSONField(default=dict, help_text='Summary of generated itinerary (num_days, num_places, etc)')),
                ('user_feedback_score', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='User rating of itinerary (1-5 stars)', null=True)),
                ('user_comments', models.TextField(blank=True, help_text='User feedback comments')),
                ('was_used', models.BooleanField(help_text='Whether user actually used this itinerary', null=True)),
                ('booking_conversion', models.BooleanField(default=False, help_text='Whether user completed booking from this itinerary')),
                ('regenerated', models.BooleanField(default=False, help_text='Whether user regenerated the itinerary (signal of dissatisfaction)')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('rating', 'Star Rating'), ('like_dislike', 'Like/Dislike'), ('comment', 'Text Comment'), ('regenerate', 'Regenerated Itinerary'), ('booking', 'Completed Booking')], max_length=20)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1-5 star rating', null=True)),
                ('liked', models.BooleanField(help_text='True for like, False for dislike, None for not applicable', null=True)),
                ('comment', models.TextField(blank=True, help_text="User's detailed feedback")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation_log', models.OneToOneField(help_text='Reference to generation event', on_delete=django.db.models.deletion.CASCADE, related_name='user_feedback', to='itineraries.aigenerationlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRankerTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(choices=[('synthetic', 'Synthetic (from heuristic)'), ('user_feedback', 'Real (from user feedback)'), ('interaction', 'Implicit (from user interactions)')], max_length=20)),
                ('user_mood', models.CharField(max_length=20)),
                ('user_interests', models.JSONField(default=list)),
                ('user_budget', models.CharField(max_length=20)),
                ('place_id', models.CharField(max_length=100)),
                ('place_category', models.CharField(max_length=50)),
                ('place_rating', models.FloatField()),
                ('place_popularity', models.FloatField()),
                ('context_day_index', models.IntegerField()),
                ('context_time_of_day', models.CharField(max_length=20)),
                ('relevance_label', models.FloatField(help_text='0-1 score indicating how relevant this place was (1=very relevant)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used_in_training', models.BooleanField(default=False)),
                ('generation_log', models.ForeignKey(blank=True, help_text='Reference to generation event that produced this sample', null=True, on_delete=django.db.models.deletion.CASCADE, to='itineraries.aigenerationlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('emotion', 'Emotion Detection'), ('ranker', 'Learning-to-Rank'), ('llm', 'LLM Enhancement')], max_length=20)),
                ('version_id', models.CharField(db_index=True, help_text='e.g., emotion-v1.2.3, ranker-v2.1.0', max_length=50, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('training_start_date', models.DateTimeField(blank=True, null=True)),
                ('training_end_date', models.DateTimeField(blank=True, null=True)),
                ('training_samples', models.IntegerField(help_text='Number of samples used for training', null=True)),
                ('validation_accuracy', models.FloatField(help_text='Validation accuracy (0-1)', null=True)),
                ('validation_ndcg', models.FloatField(help_text='NDCG score for ranking (0-1)', null=True)),
                ('validation_metrics', models.JSONField(default=dict, help_text='Additional validation metrics')),
                ('model_path', models.CharField(blank=True, help_text='S3 path or local path to model file', max_length=500)),
                ('config', models.JSONField(default=dict, help_text='Model hyperparameters and configuration')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated'), ('experimental', 'Experimental'), ('training', 'Training')], default='experimental', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Release notes or changes')),
                ('usage_count', models.BigIntegerField(default=0, help_text='Number of predictions made with this model')),
                ('last_used', models.DateTimeField(help_text='Last usage timestamp', null=True)),
            ],
            options={
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['model_type', '-created_date'], name='itineraries_model_t_ec3fb0_idx'), models.Index(fields=['status'], name='itineraries_status_b47609_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='aigenerationlog',
            index=models.Index(fields=['user_id', '-created_at'], name='itineraries_user_id_b395db_idx'),
        ),
        migrations.AddIndex(
            model_name='aigenerationlog',
            index=models.Index(fields=['status'], name='itineraries_status_76faa7_idx'),
        ),
        migrations.AddIndex(
            model_name='aigenerationlog',
            index=models.Index(fields=['final_mood'], name='itineraries_final_m_3aaba1_idx'),
        ),
        migrations.AddIndex(
            model_name='aiuserfeedback',
            index=models.Index(fields=['generation_log', 'feedback_type'], name='itineraries_generat_c6671d_idx'),
        ),
        migrations.AddIndex(
            model_name='airankertrainingdata',
            index=models.Index(fields=['data_source', 'is_used_in_training'], name='itineraries_data_so_948162_idx'),
        ),
    ]
