# Generated by Django 4.2.7 on 2026-03-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_notification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment'), ('itinerary', 'Itinerary'), ('review', 'Review'), ('promo', 'Promotion'), ('system', 'System')], default='system', max_length=20),
        ),
    ]
