# Generated by Django 4.2.7 on 2026-03-27 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_user_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
    ]
