# Generated by Django 4.2.7 on 2026-01-26 19:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_comprehensive_hotel_booking_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='roomtype',
            name='unique_hotel_roomtype',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='hotels_book_user_id_c709d3_idx',
            old_name='hotels_book_user_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='hotels_book_hotel_i_61bfaa_idx',
            old_name='hotels_book_hotel_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='hotels_book_status_d40c47_idx',
            old_name='hotels_book_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='hotels_paym_status_eb338e_idx',
            old_name='hotels_pay_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='hotels_paym_stripe__a783af_idx',
            old_name='hotels_pay_intent_idx',
        ),
        migrations.RenameIndex(
            model_name='roomtype',
            new_name='hotels_room_hotel_i_e7d0b4_idx',
            old_name='hotels_roo_hotel_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, help_text='Stripe Checkout Session ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rooms_booked',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='roomtype',
            unique_together={('hotel', 'type')},
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['city'], name='hotels_hote_city_da33bc_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['name'], name='hotels_hote_name_c9f1ff_idx'),
        ),
    ]
