# Generated by hand for safety app bootstrap

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('authentication', '0007_remove_user_phone'),
        ('hotels', '0010_booking_cancellation_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('SAFE', 'Safe'), ('RISK', 'Risk Detected'), ('SOS', 'SOS Triggered')], db_index=True, default='SAFE', max_length=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_tracking_enabled', models.BooleanField(default=True)),
                ('is_data_sharing_enabled', models.BooleanField(default=True)),
                ('latest_latitude', models.FloatField(blank=True, null=True)),
                ('latest_longitude', models.FloatField(blank=True, null=True)),
                ('latest_speed_mps', models.FloatField(blank=True, null=True)),
                ('latest_accuracy_m', models.FloatField(blank=True, null=True)),
                ('latest_heading', models.FloatField(blank=True, null=True)),
                ('latest_point_at', models.DateTimeField(blank=True, null=True)),
                ('last_moved_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('last_user_ack_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_sessions', to='hotels.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_sessions', to='authentication.user')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyRiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(choices=[('ABNORMAL_STOP', 'Abnormal Stop'), ('ROUTE_DEVIATION', 'Route Deviation'), ('HIGH_RISK_ZONE', 'High Risk Zone'), ('NO_ACTIVITY', 'No Activity'), ('MANUAL_SOS', 'Manual SOS'), ('SYSTEM_ESCALATION', 'System Escalation')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('message', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('requires_user_ack', models.BooleanField(default=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_events', to='safety.safetysession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyLocationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed_mps', models.FloatField(blank=True, null=True)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('GPS', 'GPS'), ('NETWORK', 'Network')], default='GPS', max_length=12)),
                ('client_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_points', to='safety.safetysession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('SOS', 'Manual SOS'), ('AI_ESCALATION', 'AI Escalation')], db_index=True, max_length=20)),
                ('emergency_type', models.CharField(blank=True, default='general', max_length=80)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='safety.safetysession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_incidents', to='authentication.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='safetysession',
            index=models.Index(fields=['user', 'is_active'], name='safety_safe_user_id_0626d9_idx'),
        ),
        migrations.AddIndex(
            model_name='safetysession',
            index=models.Index(fields=['status', 'is_active'], name='safety_safe_status_6f6e59_idx'),
        ),
        migrations.AddIndex(
            model_name='safetysession',
            index=models.Index(fields=['-updated_at'], name='safety_safe_updated_8f5ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyriskevent',
            index=models.Index(fields=['session', '-created_at'], name='safety_safe_session_d84d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyriskevent',
            index=models.Index(fields=['risk_type', 'is_resolved'], name='safety_safe_risk_ty_2787f4_idx'),
        ),
        migrations.AddIndex(
            model_name='safetylocationpoint',
            index=models.Index(fields=['session', '-created_at'], name='safety_safe_session_e5d2ce_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyincident',
            index=models.Index(fields=['status', '-created_at'], name='safety_safe_status_1ec455_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyincident',
            index=models.Index(fields=['user', '-created_at'], name='safety_safe_user_id_20f67f_idx'),
        ),
    ]
