# Generated by Django 4.2.7 on 2026-03-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100, unique=True)),
                ('temperature', models.FloatField()),
                ('condition', models.CharField(max_length=100)),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('icon_code', models.CharField(max_length=10)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weather Cache',
                'verbose_name_plural': 'Weather Caches',
                'indexes': [models.Index(fields=['city', '-updated_at'], name='weather_wea_city_f08af3_idx')],
            },
        ),
    ]
